-- Compétences cycle 3
local competencesC3 = {
  Ca01 = "Calculer des volumes",
  Ca02 = "Calculer des aires",
  Ca03 = "Calculer des périmètres",
  Ca04 = "Déterminer si un nombre entier est un multiple ou diviseur d’un autre nombre entier",
  Ca05 = "Mobiliser les connaissances pour déterminer des grandeurs géométriques",
  Ca06 = "Calculer avec les nombres décimaux",
  Ca07 = "Calculer avec les fractions",
  Ca08 = "Effectuer mentalement, à la main, ou à l’aide d’une calculatrice en respectant les priorités opératoires",
  Ca09 = "Calculer une quatrième proportionnelle",
  Ch01 = "Extraire d’un document les informations utiles",
  Ch02 = "S’engager dans une démarche scientifique (manipuler, expérimenter, etc.)",
  Ch03 = "Tester, essayer plusieurs pistes de résolution",
  Ch04 = "Décomposer un problème en sous problèmes",
  Co01 = "Expliquer à l’oral ou à l’écrit sa démarche son raisonnement, etc.",
  Co02 = "Restituer des connaissances",
  Mo01 = "Modéliser et résoudre des problèmes mettant en jeu la divisibilité ",
  Mo02 = "Reconnaître une situation de proportionnalité ou de non-proportionnalité ",
  Mo03 = "Utiliser un logiciel (tableur, logiciel de géométrie dynamique, logiciel de programmation…)",
  Ra01 = "Mener des raisonnements en utilisant des propriétés des figures, des configurations",
  Ra02 = "Résoudre des problèmes impliquant des grandeurs variées",
  Ra03 = "Manipuler l’algorithmique",
  Re01 = "Construire et mettre en relation différentes représentations des solides",
  Re02 = "Comprendre les effets d’une transformation (conservations, grandeurs géométriques)",
  Re03 = "Transformer une figure par symétrie axiale",
  Re04 = "Identifier les axes de symétrie d’une figure",
  Re05 = "Mettre en œuvre et écrire un protocole de construction ",
  Re06 = "Construire une figure géométrique en utilisant les informations données",
  Re07 = "Construire une figure géométrique à main levée en utilisant le codage",
  Re08 = "Mesurer, construire un angle à l’aide du rapporteur",
  Re09 = "Lire, interpréter et représenter des données",
  Re10 = "Se repérer sur une demi-droite graduée, dans le plan",
  Re11 = "Utiliser différentes écritures/représentations d’un nombre (entier, décimales, fractionnaires…)",
  Re12 = "Comparer, ranger, encadrer des nombres",
  Re13 = "Effectuer des conversions d’unités de longueurs, d’aires, de volumes et de durées",
  Re14 = "Utiliser l’échelle d’une carte"
}
-- Compétences cycle 4
local competencesC4 = {
  Ca01="Calculer des volumes",
  Ca02="Calculer des aires",
  Ca03="Calculer des périmètres",
  Ca04="Substituer une valeur à une variable",
  Ca05="Réduire une expression littérale",
  Ca06="Utiliser la propriété de distributivité pour développer un produit, factoriser une somme",
  Ca07="Factoriser une expression du type a²-b² et développer des expressions du type (a+b)(a-b)",
  Ca08="Résoudre algébriquement une équation du premier degré, équations produits ou se ramenant à x²=a",
  Ca09="Décomposer un nombre entier en produit de facteurs premiers",
  Ca10="Simplifier une fraction pour la rendre irréductible",
  Ca11="Utiliser les puissances d’exposants positifs ou négatifs d’un nombre pour simplifier l’écriture des produits",
  Ca12="Déterminer si un nombre entier est un multiple ou diviseur d’un autre nombre entier",
  Ca13="Calculer l’image d’un nombre à l’aide d’une formule.",
  Ca14="Déterminer un antécédent de manière algébrique",
  Ca15="Mobiliser les connaissances pour déterminer des grandeurs géométriques",
  Ca16="Déterminer la moyenne, la médiane et l’étendue d’une série",
  Ca17="Calculer des effectifs et des fréquences",
  Ca18="Calculer avec les nombres décimaux relatifs",
  Ca19="Effectuer mentalement, à la main, ou à l’aide d’une calculatrice en respectant les priorités opératoires",
  Ca20="Utiliser les carrés parfaits de 1 à 144 et la racine carrée",
  Ca21="Utiliser la calculatrice pour déterminer une valeur approchée de la racine carrée d’un nombre positif",
  Ca22="Calculer avec les nombres rationnels : addition, soustraction, multiplication, division",
  Ca23="Calculer une quatrième proportionnelle",
  Ca24="Utiliser un rapport d’agrandissement ou de réduction pour calculer des longueurs, des aires, des volumes",
  Ch01="Extraire d’un document les informations utiles",
  Ch02="S’engager dans une démarche scientifique (manipuler, expérimenter, etc.)",
  Ch03="Tester, essayer plusieurs pistes de résolution",
  Ch04="Décomposer un problème en sous problèmes",
  Co01="Expliquer à l’oral ou à l’écrit sa démarche son raisonnement, etc.",
  Co02="Écrire un script correspondant à un programme de calculs.",
  Mo01="Produire une expression littérale pour élaborer une formule ou traduire un programme de calcul",
  Mo02="Introduire une lettre pour désigner une valeur inconnue et mettre un problème en équation",
  Mo03="Modéliser et résoudre des problèmes mettant en jeu la divisibilité ",
  Mo04="Résoudre des problèmes de puissances, notamment en utilisant la notation scientifique",
  Mo05="Déterminer des probabilités pour des expériences simples à une ou deux épreuves.",
  Mo06="Faire le lien entre stabilisation des fréquences et des probabilités.",
  Mo07="Reconnaître des évènements (certains, impossibles, contraires…)",
  Mo08="Reconnaître une situation de proportionnalité ou de non-proportionnalité ",
  Mo09="Utiliser un logiciel (tableur, logiciel de géométrie dynamique, logiciel de programmation…)",
  Ra01="Résoudre des problèmes en utilisant la proportionnalité",
  Ra02="Résoudre des problèmes modélisés par des fonctions",
  Ra03="Mener des raisonnements en utilisant des propriétés des figures, des configurations",
  Ra04="Résoudre des problèmes impliquant des grandeurs variées",
  Ra05="Manipuler l’algorithmique",
  Re01="Construire et mettre en relation différentes représentations des solides",
  Re02="Comprendre les effets d’une transformation (conservations, grandeurs géométriques)",
  Re03="Transformer une figure",
  Re04="Identifier des transformations dans des frises et des pavages et des rosaces",
  Re05="Déterminer images/antécédents à partir d’une représentation graphique ou d’un tableau",
  Re06="Représenter graphiquement une fonction",
  Re07="Interpréter les paramètres d’une fonction affine suivant l’allure de sa courbe représentative",
  Re08="Mettre en œuvre et écrire un protocole de construction ",
  Re09="Lire, interpréter et représenter des données",
  Re10="Interpréter la moyenne, la médiane et l’étendue d’une série",
  Re11="Se repérer sur une droite graduée, dans le plan, sur un pavé droit, sur une sphère",
  Re12="Utiliser différentes écritures/représentations d’un nombre (décimales, fractionnaires, scientifiques…)",
  Re13="Comparer, ranger, encadrer des nombres",
  Re14="Effectuer des conversions d’unités de longueurs, d’aires, de volumes et de durées",
  Re15="Utiliser l’échelle d’une carte"
}

-- fonctions pour retourner la compétence en fonction de son code
local function print_competence_c3(code)
  tex.sprint(competencesC3[code])
end
local function print_competence_c4(code)
  tex.sprint(competencesC4[code])
end

return { c3 = print_competence_c3, c4 = print_competence_c4 }